"use strict";
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OPSEOraclePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian12 = require("obsidian");

// src/core/adventure-state.ts
var DEFAULT_SETTINGS = {
  adventures: {},
  activeAdventureId: null,
  randomMode: "dice",
  autoInsert: true,
  language: "es",
  history: [],
  dungeons: {},
  regions: {}
};
var AdventureStateManager = class {
  constructor(settings, saveCallback) {
    __publicField(this, "settings");
    __publicField(this, "saveCallback");
    this.settings = settings;
    this.saveCallback = saveCallback;
  }
  async createAdventure(title, system, genre, notePath) {
    const id = crypto.randomUUID();
    const adventure = {
      id,
      title,
      system,
      genre,
      activeNotePath: notePath,
      timestamp: Date.now(),
      sceneRank: 1,
      threads: []
    };
    this.settings.adventures[notePath] = adventure;
    this.settings.activeAdventureId = id;
    await this.saveCallback(this.settings);
    return adventure;
  }
  getAdventure(notePath) {
    const adventure = this.settings.adventures[notePath];
    if (adventure) {
      if (adventure.sceneRank === void 0)
        adventure.sceneRank = 1;
      if (!adventure.threads)
        adventure.threads = [];
    }
    return adventure;
  }
  async updateActiveAdventure(notePath) {
    const adventure = this.getAdventure(notePath);
    if (adventure) {
      this.settings.activeAdventureId = adventure.id;
      await this.saveCallback(this.settings);
    }
  }
  getActiveAdventure() {
    if (!this.settings.activeAdventureId)
      return null;
    return Object.values(this.settings.adventures).find((a) => a.id === this.settings.activeAdventureId) || null;
  }
  async addThread(notePath, thread) {
    const adventure = this.getAdventure(notePath);
    if (adventure) {
      adventure.threads.push(thread);
      await this.saveCallback(this.settings);
    }
  }
  async removeThread(notePath, index) {
    const adventure = this.getAdventure(notePath);
    if (adventure && adventure.threads[index]) {
      adventure.threads.splice(index, 1);
      await this.saveCallback(this.settings);
    }
  }
  async setSceneRank(notePath, rank) {
    const adventure = this.getAdventure(notePath);
    if (adventure) {
      adventure.sceneRank = Math.max(1, Math.min(6, rank));
      await this.saveCallback(this.settings);
    }
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");

// src/i18n/en.ts
var en = {
  SETTINGS: {
    TITLE: "OPSE Oracle Settings",
    RANDOM_MODE: "Randomization Mode",
    RANDOM_MODE_DESC: "Choose between dice (d6) or a virtual card deck (as in OPSE v1.6).",
    DICE: "Dice (d6)",
    CARDS: "Cards (Standard Deck)",
    PERSISTENT_DECK: "Persistent Deck (runs out)",
    AUTO_INSERT: "Auto-insert",
    AUTO_INSERT_DESC: "If enabled, results will be automatically inserted into the active note.",
    LANGUAGE: "Language",
    LANGUAGE_DESC: "Select the plugin language.",
    OPEN_CONTROL: "Open control panel",
    OPEN_HISTORY: "Open history",
    OPEN_EXPLORATION: "Open exploration tracker"
  },
  ADVENTURE: {
    NEW: "Start New Adventure",
    TITLE: "Title",
    SYSTEM: "RPG System",
    GENRE: "Genre / Tone",
    PROTAGONISTS: "Protagonists",
    PROMPT: "Starting Premise",
    START: "Start",
    NOTE_HEADER: "## Premise",
    SCENE_HEADER: "## Scene Log",
    NPC: "Generate NPC",
    HOOK: "Generate Plot Hook",
    DOUBLE_FOCUS: "Double Focus",
    PLOT_TWIST: "Plot Twist",
    FLAVOR: "Atmosphere / Weather",
    GENERIC: "Generic Content",
    NPC_FIELDS: {
      IDENTITY: "Identity",
      GOAL: "Goal",
      TRAIT: "Notable Trait",
      ATTITUDE: "Attitude",
      TOPIC: "Conversation Topic"
    }
  },
  HELP: {
    TITLE: "Procedures & Help",
    SCENE_STEREOTYPE: "1. Imagine the scene stereotype.",
    SCENE_ALTERED: "2. Check if the scene is Altered (1d6 <= current Scene).",
    EVENT_TRIGGER: "3. Roll a Random Event if a check fails or you are stuck.",
    GM_MOVES: "4. Use GM Moves to advance threats or complicate things."
  },
  EXPORT: {
    BUTTON: "Export Session",
    SUCCESS: "Session exported to: ",
    ERROR: "Error exporting session."
  },
  SCENE: {
    NEW: "Prepare New Scene",
    OBJECTIVE: "Scene Objective",
    OBJECTIVE_DESC: "What are the characters trying to achieve?",
    LOCATION: "Location",
    GENERATE: "Generate Scene",
    ALTERED_NOTICE: "ALTERED SCENE!",
    ALTERED_ONLY: "Altered Scene",
    CHECK_ALTERATION: "Check Alteration",
    NOT_ALTERED: "Normal Scene",
    COMPLICATION: "Scene Complication",
    COMPLICATION_BTN: "Scene Complication"
  },
  ORACLE: {
    TITLE: "Oracles",
    FOCUS_TITLE: "Oracle (FOCUS)",
    ACTION: "Action",
    DETAIL: "Detail",
    YES: "Yes",
    NO: "No",
    BUT: "but...",
    AND: "and...",
    YESNO_TITLE: "Ask Oracle (Yes/No)",
    QUESTION: "Question",
    QUESTION_DESC: "What do you want to know?",
    LIKELIHOOD: "Likelihood",
    PROBABLE: "Probable (3+)",
    EVEN: "Even (4+)",
    IMPROBABLE: "Improbable (5+)",
    ASK: "Ask",
    HOW_MUCH: "How Much? / What level?",
    SCALES: ["Scarce", "Low", "Normal", "Notable", "Extraordinary", "Extreme"]
  },
  DASHBOARD: {
    TITLE: "OPSE Dashboard",
    GENERATORS: "Generators",
    SESSION: "Session",
    HISTORY: "OPSE History Log",
    HELP: "Help",
    RANK: "Scene Rank",
    THREADS: "Threads / Goals",
    NEW_THREAD: "New thread...",
    NO_HISTORY: "No history yet.",
    BARAJAR: "Shuffle",
    EXPORTAR: "Export Log",
    SHUFFLE_SUCCESS: "Deck shuffled."
  },
  METADATA: {
    ANSWER: "Answer",
    MOD: "Mod",
    DICE: "",
    LIKELIHOOD: "Likelihood",
    COMPLICATION: "Complication",
    ALTERED: "Altered",
    NORMAL: "Normal",
    RESULT: "Result",
    DOMAIN: "Domain",
    NOTE: "Note",
    RAW: "Raw"
  },
  COMMON: {
    COPY: "Copy",
    INSERT: "Insert",
    REROLL: "Re-roll",
    PIN: "Pin",
    UNPIN: "Unpin",
    COPIED: "Copied to clipboard",
    JOKER_NOTICE: "JOKER! A Random Event is automatically triggered."
  },
  TABLES: {
    COMPLICATIONS: [
      "Hostile forces (an enemy or group opposes you)",
      "Obstacle (something blocks physical path or progress)",
      "Wouldn't it suck if... (ironic or unforeseen complication)",
      "NPC acts (a character takes the initiative)",
      "Not everything is as it seems (hidden revelation)",
      "As planned (no immediate setbacks)"
    ],
    ALTERED: {
      "1": "An important detail of the scene is improved or worsened in some way",
      "2": "The environment is different",
      "3": "Unexpected NPCs are present",
      "4": "Add a **Scene Complication**",
      "5": "Add a Beat Move",
      "6": "Add a Random Event"
    },
    ACTIONS: {
      "2": "Seek",
      "3": "Oppose",
      "4": "Communicate",
      "5": "Move",
      "6": "Harm",
      "7": "Create",
      "8": "Reveal",
      "9": "Command",
      "10": "Take",
      "J": "Protect",
      "Q": "Assist",
      "K": "Transform",
      "A": "Deceive"
    },
    DETAILS: {
      "2": "Small",
      "3": "Large",
      "4": "Ancient",
      "5": "Recent",
      "6": "Valuable",
      "7": "Worthless",
      "8": "Dangerous",
      "9": "Unsavory",
      "10": "Important",
      "J": "Simple",
      "Q": "Complex",
      "K": "Magical",
      "A": "Mundane"
    },
    THEMES: {
      "2": "Peace",
      "3": "Conflict",
      "4": "Power",
      "5": "Time",
      "6": "Fear",
      "7": "Death",
      "8": "Life",
      "9": "Money",
      "10": "Knowledge",
      "J": "Love",
      "Q": "War",
      "K": "Fate",
      "A": "Chaos"
    },
    DOMAINS: {
      "Hearts": "Mystic (Feelings, magic, health, spiritual)",
      "Clubs": "Technical (Tools, mind, plans, science)",
      "Diamonds": "Social (People, relationships, trade, law)",
      "Spades": "Physical (Combat, environment, objects, strength)"
    },
    GM_MOVES_BEAT: [
      "Foreshadow trouble",
      "Offer an opportunity",
      "Reveal a new detail",
      "Advance a threat",
      "Put someone in a spot",
      "Announce an imminent danger"
    ],
    GM_MOVES_FAILURE: [
      "Cause harm",
      "Spend resources",
      "Separate them",
      "Turn their move against them",
      "Show the downsides of their class/gear",
      "Make a threat move"
    ],
    PLOT_TWIST: [
      "An ally turns out to be a traitor",
      "The goal is not what it seemed",
      "A third party unexpectedly appears",
      "Time is running out faster than expected",
      "A victory turns into a complication",
      "An enemy offers a truce"
    ],
    FLAVOR: {
      ATMOSPHERE: ["Tense", "Melancholic", "Oppressive", "Hopeful", "Mysterious", "Chaotic"],
      WEATHER: ["Heavy rain", "Thick fog", "Scorching sun", "Freezing wind", "Thunderstorm", "Clear skies"]
    },
    HOOKS: {
      TITLE: "Plot Hook",
      GOAL_LABEL: "Goal",
      ADVERSARY_LABEL: "Adversaries",
      REWARD_LABEL: "Rewards",
      GOAL: ["Eliminate a threat", "Learn the truth", "Recover something of value", "Escort or delivery for safety", "Restore something broken", "Save a clear ally in danger"],
      ADVERSARY: ["A powerful organization", "Outlaws", "Guardians", "Local population", "Hordes or enemy forces", "A new or recurring villain"],
      REWARD: ["Money or goods", "Money or goods", "Knowledge or Secrets", "Help an ally", "Advance a plot arc", "A unique object of power"]
    }
  }
};

// src/i18n/es.ts
var es = {
  SETTINGS: {
    TITLE: "Configuraci\xF3n de OPSE Oracle",
    RANDOM_MODE: "Modo de Aleatorizaci\xF3n",
    RANDOM_MODE_DESC: "Elige entre dados (d6) o una baraja de cartas virtual (como en OPSE v1.6).",
    DICE: "Dados (d6)",
    CARDS: "Cartas (Baraja Est\xE1ndar)",
    PERSISTENT_DECK: "Baraja Persistente (se agota)",
    AUTO_INSERT: "Inserci\xF3n autom\xE1tica",
    AUTO_INSERT_DESC: "Si est\xE1 activado, los resultados se insertar\xE1n autom\xE1ticamente en la nota activa.",
    LANGUAGE: "Idioma",
    LANGUAGE_DESC: "Selecciona el idioma del plugin.",
    OPEN_CONTROL: "Abrir panel de control",
    OPEN_HISTORY: "Abrir historial",
    OPEN_EXPLORATION: "Abrir rastreador de exploraci\xF3n"
  },
  ADVENTURE: {
    NEW: "Nueva Aventura",
    TITLE: "T\xEDtulo",
    SYSTEM: "Sistema RPG",
    GENRE: "G\xE9nero / Tono",
    PROTAGONISTS: "Protagonistas",
    PROMPT: "Premisa Inicial",
    START: "Comenzar",
    NOTE_HEADER: "## Premisa",
    SCENE_HEADER: "## Registro de Escenas",
    NPC: "Generar PNJ",
    HOOK: "Generar V\xEDnculo/Misi\xF3n",
    DOUBLE_FOCUS: "Foco Doble",
    PLOT_TWIST: "Giro de Trama",
    FLAVOR: "Ambiente / Clima",
    GENERIC: "Contenido Gen\xE9rico",
    NPC_FIELDS: {
      IDENTITY: "Identidad",
      GOAL: "Objetivo",
      TRAIT: "Rasgo Notable",
      ATTITUDE: "Actitud",
      TOPIC: "Tema de conversaci\xF3n"
    }
  },
  HELP: {
    TITLE: "Procedimientos y Ayuda",
    SCENE_STEREOTYPE: "1. Imagina el estereotipo de la escena.",
    SCENE_ALTERED: "2. Comprueba si la escena est\xE1 Alterada (1d6 <= Rango actual).",
    EVENT_TRIGGER: "3. Lanza un Evento Aleatorio si una prueba falla o te bloqueas.",
    GM_MOVES: "4. Usa los Movimientos del DJ para avanzar amenazas o complicar las cosas."
  },
  EXPORT: {
    BUTTON: "Exportar Sesi\xF3n",
    SUCCESS: "Sesi\xF3n exportada a: ",
    ERROR: "Error al exportar la sesi\xF3n."
  },
  SCENE: {
    NEW: "Preparar Nueva Escena",
    OBJECTIVE: "Objetivo de la Escena",
    OBJECTIVE_DESC: "\xBFQu\xE9 intentan lograr los personajes?",
    LOCATION: "Ubicaci\xF3n",
    GENERATE: "Generar Escena",
    ALTERED_NOTICE: "\xA1ESCENA ALTERADA!",
    ALTERED_ONLY: "Escena Alterada",
    CHECK_ALTERATION: "Chequear Alteraci\xF3n",
    NOT_ALTERED: "Escena Normal",
    COMPLICATION: "Complicaci\xF3n de la Escena",
    COMPLICATION_BTN: "Complicaci\xF3n Escena"
  },
  ORACLE: {
    TITLE: "Or\xE1culos",
    FOCUS_TITLE: "Or\xE1culo (ENFOQUE)",
    ACTION: "Acci\xF3n",
    DETAIL: "Detalle",
    YES: "S\xED",
    NO: "No",
    BUT: "pero...",
    AND: "y...",
    YESNO_TITLE: "Preguntar al Or\xE1culo (S\xED/No)",
    QUESTION: "Pregunta",
    QUESTION_DESC: "\xBFQu\xE9 quieres saber?",
    LIKELIHOOD: "Probabilidad",
    PROBABLE: "Probable (3+)",
    EVEN: "A nivel (4+)",
    IMPROBABLE: "Improbable (5+)",
    ASK: "Preguntar",
    HOW_MUCH: "\xBFCu\xE1nto? / \xBFQu\xE9 nivel?",
    SCALES: ["Escaso", "Bajo", "Normal", "Notable", "Extraordinario", "Extremo"]
  },
  DASHBOARD: {
    TITLE: "Dashboard de OPSE",
    GENERATORS: "Generadores",
    SESSION: "Sesi\xF3n",
    HISTORY: "Historial de OPSE",
    HELP: "Ayuda",
    RANK: "Rango Escena",
    THREADS: "Hilos / Objetivos",
    NEW_THREAD: "Nuevo hilo...",
    NO_HISTORY: "Sin historial a\xFAn.",
    BARAJAR: "Barajar",
    EXPORTAR: "Exportar Log",
    SHUFFLE_SUCCESS: "Baraja barajada."
  },
  METADATA: {
    ANSWER: "Respuesta",
    MOD: "Mod",
    DICE: "",
    LIKELIHOOD: "Probabilidad",
    COMPLICATION: "Complicaci\xF3n",
    ALTERED: "Alterado",
    NORMAL: "Normal",
    RESULT: "Resultado",
    DOMAIN: "Dominio",
    NOTE: "Nota",
    RAW: "Crudo"
  },
  COMMON: {
    COPY: "Copiar",
    INSERT: "Insertar",
    REROLL: "Relanzar",
    PIN: "Fijar",
    UNPIN: "Desfijar",
    COPIED: "Copiado al portapapeles",
    JOKER_NOTICE: "\xA1COMOD\xCDN! Se dispara un Evento Aleatorio autom\xE1ticamente."
  },
  TABLES: {
    COMPLICATIONS: [
      "Fuerzas hostiles se oponen a ti",
      "Un obst\xE1culo bloquea tu camino",
      "\xBFNo ser\xEDa una mierda si...",
      "Un PNJ act\xFAa repentinamente",
      "No todo es lo que parece ",
      "Las cosas van como se planearon"
    ],
    ALTERED: {
      "1": "Un detalle importante de la escena se mejora o empeora de alguna manera",
      "2": "El entorno es diferente",
      "3": "Hay presentes PNJs inesperados",
      "4": "A\xF1ade una **Complicaci\xF3n de Escena**",
      "5": "A\xF1ade un Movimiento de Ritmo",
      "6": "A\xF1ade un Evento Aleatorio"
    },
    PLOT_TWIST: [
      "Un aliado resulta ser un traidor",
      "El objetivo no es lo que parec\xEDa",
      "Aparece un tercer bando inesperado",
      "El tiempo se agota m\xE1s r\xE1pido de lo previsto",
      "Una victoria se convierte en una complicaci\xF3n",
      "Un enemigo ofrece una tregua"
    ],
    FLAVOR: {
      ATMOSPHERE: ["Tenso", "Melanc\xF3lico", "Opresivo", "Esperanzador", "Misterioso", "Ca\xF3tico"],
      WEATHER: ["Lluvia torrencial", "Niebla densa", "Sol abrasador", "Viento helado", "Tormenta el\xE9ctrica", "Despejado"]
    },
    ACTIONS: {
      "2": "Buscar",
      "3": "Oponerse",
      "4": "Comunicar",
      "5": "Mover",
      "6": "Da\xF1ar",
      "7": "Crear",
      "8": "Revelar",
      "9": "Comandar",
      "10": "Tomar",
      "J": "Proteger",
      "Q": "Asistir",
      "K": "Transformar",
      "A": "Enga\xF1ar"
    },
    DETAILS: {
      "2": "Peque\xF1o",
      "3": "Grande",
      "4": "Antiguo",
      "5": "Reciente",
      "6": "Valioso",
      "7": "In\xFAtil",
      "8": "Peligroso",
      "9": "Desagradable",
      "10": "Importante",
      "J": "Simple",
      "Q": "Complejo",
      "K": "M\xE1gico",
      "A": "Mundano"
    },
    THEMES: {
      "2": "Paz",
      "3": "Conflicto",
      "4": "Poder",
      "5": "Tiempo",
      "6": "Miedo",
      "7": "Muerte",
      "8": "Vida",
      "9": "Dinero",
      "10": "Conocimiento",
      "J": "Amor",
      "Q": "Guerra",
      "K": "Destino",
      "A": "Caos"
    },
    DOMAINS: {
      "Hearts": "M\xEDstico (Sentimientos, magia, salud, espiritual)",
      "Clubs": "T\xE9cnico (Herramientas, mente, planes, ciencia)",
      "Diamonds": "Social (Gente, relaciones, comercio, ley)",
      "Spades": "F\xEDsico (Combate, entorno, objetos, fuerza)"
    },
    GM_MOVES_BEAT: [
      "Presentir problemas",
      "Ofrecer una oportunidad",
      "Revelar un detalle nuevo",
      "Avanzar una amenaza",
      "Poner a alguien en un aprieto",
      "Anunciar un peligro inminente"
    ],
    GM_MOVES_FAILURE: [
      "Causar da\xF1o",
      "Gastar recursos",
      "Separarlos",
      "Girar su movimiento contra ellos",
      "Mostrar las desventajas de su equipo/clase",
      "Hacer un movimiento de amenaza"
    ],
    HOOKS: {
      TITLE: "Gancho Argumental",
      GOAL_LABEL: "Objetivo",
      ADVERSARY_LABEL: "Adversarios",
      REWARD_LABEL: "Recompensas",
      GOAL: ["Elimina una amenaza", "Aprende la verdad", "Recupera algo de valor", "Escolta o entrega por seguridad", "Restaura algo roto", "Salva a un aliado en peligro"],
      ADVERSARY: ["Una poderosa organizaci\xF3n", "Forajidos", "Guardianes", "Poblaci\xF3n local", "Hordas o fuerzas enemigas", "Un nuevo o recurrente villano"],
      REWARD: ["Dinero o bienes", "Dinero o bienes", "Conocimientos o Secretos", "Ayuda a un aliado", "Avanza en un arco argumental", "Un objeto \xFAnico de poder"]
    }
  }
};

// src/i18n/i18n.ts
var I18n = class {
  static setLanguage(lang) {
    this.lang = lang;
  }
  static getLanguage() {
    return this.lang;
  }
  static t() {
    return this.lang === "es" ? es : en;
  }
};
__publicField(I18n, "lang", "en");
var t = () => I18n.t();

// src/settings.ts
var OPSESettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const strings = t().SETTINGS;
    containerEl.createEl("h2", { text: strings.TITLE });
    new import_obsidian.Setting(containerEl).setName(strings.LANGUAGE).setDesc(strings.LANGUAGE_DESC).addDropdown((dropdown) => dropdown.addOption("en", "English").addOption("es", "Espa\xF1ol").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      I18n.setLanguage(value);
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName(strings.RANDOM_MODE).setDesc(strings.RANDOM_MODE_DESC).addDropdown((dropdown) => dropdown.addOption("dice", strings.DICE).addOption("cards", strings.CARDS).addOption("persistent_deck", strings.PERSISTENT_DECK).setValue(this.plugin.settings.randomMode).onChange(async (value) => {
      this.plugin.settings.randomMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(strings.AUTO_INSERT).setDesc(strings.AUTO_INSERT_DESC).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoInsert).onChange(async (value) => {
      this.plugin.settings.autoInsert = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Gesti\xF3n de Datos" });
    new import_obsidian.Setting(containerEl).setName("L\xEDmite de historial").addSlider((slider) => slider.setLimits(10, 500, 10).setValue(this.plugin.settings.history.length > 100 ? this.plugin.settings.history.length : 100).onChange(async (value) => {
      await this.plugin.historyManager.setMaxEntries(value);
    }));
    new import_obsidian.Setting(containerEl).setName("Limpiar historial").addButton((btn) => btn.setButtonText("Limpiar").setWarning().onClick(async () => {
      if (confirm("\xBFLimpiar historial?")) {
        await this.plugin.historyManager.clearHistory();
        this.plugin.refreshViews();
      }
    }));
  }
};

// src/core/history.ts
var HistoryManager = class {
  constructor(history, maxEntries, saveCallback) {
    __publicField(this, "history", []);
    __publicField(this, "maxEntries", 100);
    __publicField(this, "saveCallback");
    this.history = history;
    this.maxEntries = maxEntries;
    this.saveCallback = saveCallback;
  }
  async addEntry(entry) {
    this.history.unshift(entry);
    this.cleanup();
    await this.saveCallback(this.history);
  }
  cleanup() {
    if (this.history.length <= this.maxEntries)
      return;
    const pinned = this.history.filter((e) => e.pinned);
    const unpinned = this.history.filter((e) => !e.pinned);
    const remainingUnpinnedCount = Math.max(0, this.maxEntries - pinned.length);
    const trimmedUnpinned = unpinned.slice(0, remainingUnpinnedCount);
    this.history = [...pinned, ...trimmedUnpinned].sort((a, b) => b.timestamp - a.timestamp);
  }
  getHistory() {
    return this.history;
  }
  async clearHistory() {
    this.history = this.history.filter((e) => e.pinned);
    await this.saveCallback(this.history);
  }
  async setMaxEntries(max) {
    this.maxEntries = max;
    this.cleanup();
    await this.saveCallback(this.history);
  }
};

// src/ui/modals/adventure-modal.ts
var import_obsidian2 = require("obsidian");
var AdventureModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    __publicField(this, "plugin");
    __publicField(this, "title", "");
    __publicField(this, "system", "...");
    __publicField(this, "genre", "...");
    __publicField(this, "protagonists", "");
    __publicField(this, "startingPrompt", "");
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const strings = t().ADVENTURE;
    contentEl.createEl("h2", { text: strings.NEW });
    new import_obsidian2.Setting(contentEl).setName(strings.TITLE).addText((text) => text.onChange((value) => this.title = value));
    new import_obsidian2.Setting(contentEl).setName(strings.SYSTEM).addText((text) => text.setValue(this.system).onChange((value) => this.system = value));
    new import_obsidian2.Setting(contentEl).setName(strings.GENRE).addText((text) => text.setValue(this.genre).onChange((value) => this.genre = value));
    new import_obsidian2.Setting(contentEl).setName(strings.PROTAGONISTS).addTextArea((text) => text.onChange((value) => this.protagonists = value));
    new import_obsidian2.Setting(contentEl).setName(strings.PROMPT).addTextArea((text) => text.onChange((value) => this.startingPrompt = value));
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText(strings.START).setCta().onClick(async () => {
      await this.startAdventure();
      this.close();
    }));
  }
  async startAdventure() {
    const strings = t().ADVENTURE;
    const defaultTitle = strings.NEW;
    const fileName = (0, import_obsidian2.normalizePath)(`${this.title || defaultTitle}.md`);
    let finalPath = fileName;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(finalPath)) {
      finalPath = (0, import_obsidian2.normalizePath)(`${this.title || defaultTitle} (${counter}).md`);
      counter++;
    }
    let content = `---
opse-adventure: true
title: "${this.title || defaultTitle}"
system: "${this.system}"
genre: "${this.genre}"
protagonists: "${this.protagonists.replace(/\n/g, ", ")}"
created: ${new Date().toISOString()}
---
# ${this.title || defaultTitle}

**${strings.SYSTEM}:** ${this.system} | **${strings.GENRE}:** ${this.genre}
${this.protagonists ? `**${strings.PROTAGONISTS}:** ${this.protagonists}
` : ""}

---

${strings.NOTE_HEADER}
${this.startingPrompt || "..."}

${strings.SCENE_HEADER}

`;
    const newFile = await this.app.vault.create(finalPath, content);
    await this.plugin.adventureManager.createAdventure(this.title || defaultTitle, this.system, this.genre, newFile.path);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(newFile);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/modals/scene-modal.ts
var import_obsidian4 = require("obsidian");

// src/core/opse.ts
var OPSE = class {
  static resolveYesNo(d1, d2, likelihood) {
    const strings = t().ORACLE;
    let successThreshold = 4;
    if (likelihood === "probable")
      successThreshold = 3;
    if (likelihood === "improbable")
      successThreshold = 5;
    const isSuccess = d1 >= successThreshold;
    const answer = isSuccess ? strings.YES : strings.NO;
    let modifier;
    if (d2 === 1)
      modifier = strings.BUT;
    if (d2 === 6)
      modifier = strings.AND;
    return { answer, modifier };
  }
  static getAction(rank) {
    return t().TABLES.ACTIONS[rank] || "???";
  }
  static getDetail(rank) {
    return t().TABLES.DETAILS[rank] || "???";
  }
  static getTheme(rank) {
    return t().TABLES.THEMES[rank] || "???";
  }
  static getDomain(suit) {
    return t().TABLES.DOMAINS[suit] || "???";
  }
  static getComplication(index) {
    return t().TABLES.COMPLICATIONS[index] || "???";
  }
  static getAltered(index) {
    return t().TABLES.ALTERED[index.toString()] || "???";
  }
  static getBeatMove(index) {
    return t().TABLES.GM_MOVES_BEAT[index] || "???";
  }
  static getFailureMove(index) {
    return t().TABLES.GM_MOVES_FAILURE[index] || "???";
  }
  static getPlotTwist(index) {
    return t().TABLES.PLOT_TWIST[index] || "???";
  }
  static getAtmosphere(index) {
    return t().TABLES.FLAVOR.ATMOSPHERE[index] || "???";
  }
  static getWeather(index) {
    return t().TABLES.FLAVOR.WEATHER[index] || "???";
  }
};

// src/core/random.ts
var Random = class {
  static d(sides) {
    return Math.floor(Math.random() * sides) + 1;
  }
  static roll2d6() {
    const d1 = this.d(6);
    const d2 = this.d(6);
    return { total: d1 + d2, d1, d2 };
  }
  static drawFocus(mode, deck) {
    if (mode === "cards" || mode === "persistent_deck") {
      const card = deck.draw();
      if (card.suit === "Joker" /* Joker */) {
        return { rank: "Joker", suit: "Joker" /* Joker */, wasJoker: true };
      }
      return { rank: card.rank, suit: card.suit };
    } else {
      const rankRoll = this.d(12);
      let rank = rankRoll.toString();
      if (rankRoll === 11)
        rank = "J";
      if (rankRoll === 12)
        rank = this.d(2) === 1 ? "Q" : "K";
      if (rankRoll === 1)
        rank = "A";
      const suitRoll = this.d(4);
      const suits = ["Clubs" /* Clubs */, "Diamonds" /* Diamonds */, "Spades" /* Spades */, "Hearts" /* Hearts */];
      return { rank, suit: suits[suitRoll - 1] };
    }
  }
  static pickOne(array) {
    return array[Math.floor(Math.random() * array.length)];
  }
};

// src/utils/markdown.ts
var import_obsidian3 = require("obsidian");
var MarkdownUtils = class {
  static async insertAtCursor(app, content, targetPath) {
    let activeView = null;
    if (targetPath) {
      app.workspace.iterateAllLeaves((leaf) => {
        var _a;
        if (leaf.view instanceof import_obsidian3.MarkdownView && ((_a = leaf.view.file) == null ? void 0 : _a.path) === targetPath) {
          activeView = leaf.view;
        }
      });
    }
    if (!activeView) {
      activeView = app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    }
    if (activeView) {
      const editor = activeView.editor;
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const textToInsert = (line.trim().length > 0 ? "\n" : "") + content;
      editor.replaceRange(textToInsert, cursor);
      const lines = textToInsert.split("\n");
      if (lines.length > 1) {
        editor.setCursor({ line: cursor.line + lines.length - 1, ch: lines[lines.length - 1].length });
      } else {
        editor.setCursor({ line: cursor.line, ch: cursor.ch + textToInsert.length });
      }
    }
  }
  static async smartInsert(app, plugin, content) {
    if (!plugin.settings.autoInsert)
      return;
    const active = plugin.adventureManager.getActiveAdventure();
    await this.insertAtCursor(app, content, active == null ? void 0 : active.activeNotePath);
  }
  static formatResult(title, answer, raw, footer, interpretation) {
    let text = "";
    let label = title;
    let question = "";
    if (title.includes(":")) {
      const parts = title.split(":");
      label = parts[0].trim();
      question = parts.slice(1).join(":").trim();
    }
    if (question) {
      text += `? ${question}
`;
    } else if (label && label !== "Result") {
    }
    text += `${answer} <small>${raw}</small>
`;
    if (footer) {
      text += `*${footer}*
`;
    }
    text += `> ${interpretation || ""}

`;
    return text;
  }
  static formatSection(title) {
    return `## ${title}

`;
  }
};

// src/ui/modals/scene-modal.ts
var SceneModal = class extends import_obsidian4.Modal {
  constructor(app, plugin) {
    super(app);
    __publicField(this, "plugin");
    __publicField(this, "objective", "");
    __publicField(this, "location", "");
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const strings = t().SCENE;
    contentEl.createEl("h2", { text: strings.NEW });
    new import_obsidian4.Setting(contentEl).setName(strings.OBJECTIVE).setDesc(strings.OBJECTIVE_DESC).addText((text) => text.onChange((value) => this.objective = value));
    new import_obsidian4.Setting(contentEl).setName(strings.LOCATION).addText((text) => text.onChange((value) => this.location = value));
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText(strings.GENERATE).setCta().onClick(async () => {
      await this.generateScene();
      this.close();
    }));
  }
  async generateScene() {
    const strings = t().SCENE;
    const complicationRoll = Random.d(6);
    const complication = OPSE.getComplication(complicationRoll - 1);
    let title = `${strings.NEW}: ${this.objective || "..."}`;
    let content = `**${strings.LOCATION}:** ${this.location || "..."}
**${strings.OBJECTIVE}:** ${this.objective || "..."}

**${strings.COMPLICATION}:** ${complication}`;
    const meta = t().METADATA;
    let raw = `(1d6=${complicationRoll} [${meta.COMPLICATION}])`;
    await this.plugin.historyManager.addEntry({
      id: crypto.randomUUID(),
      answer: complication,
      question: title,
      raw,
      timestamp: Date.now(),
      type: "scene"
    });
    const markdown = MarkdownUtils.formatResult(title, content, raw);
    await MarkdownUtils.smartInsert(this.app, this.plugin, markdown);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/modals/oracle-modal.ts
var import_obsidian5 = require("obsidian");
var OracleModal = class extends import_obsidian5.Modal {
  constructor(app, plugin) {
    super(app);
    __publicField(this, "plugin");
    __publicField(this, "question", "");
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const strings = t().ORACLE;
    contentEl.createEl("h2", { text: strings.YESNO_TITLE });
    new import_obsidian5.Setting(contentEl).setName(strings.QUESTION).setDesc(strings.QUESTION_DESC).addText((text) => text.onChange((value) => this.question = value));
    const buttonRow = contentEl.createDiv({ cls: "opse-likelihood-row" });
    const btnProbable = buttonRow.createEl("button", { text: strings.PROBABLE, cls: "mod-cta" });
    btnProbable.addEventListener("click", () => {
      this.askOracle("probable");
      this.close();
    });
    const btnEven = buttonRow.createEl("button", { text: strings.EVEN, cls: "mod-cta" });
    btnEven.addEventListener("click", () => {
      this.askOracle("even");
      this.close();
    });
    const btnImprobable = buttonRow.createEl("button", { text: strings.IMPROBABLE, cls: "mod-cta" });
    btnImprobable.addEventListener("click", () => {
      this.askOracle("improbable");
      this.close();
    });
  }
  async askOracle(likelihood) {
    const strings = t().ORACLE;
    const meta = t().METADATA;
    const roll = Random.roll2d6();
    const { answer, modifier } = OPSE.resolveYesNo(roll.d1, roll.d2, likelihood);
    let title = `${strings.YESNO_TITLE}: ${this.question || "..."}`;
    let content = `${answer}${modifier ? ` ${modifier}` : ""}`;
    let raw = `(2d6=${roll.d1 + roll.d2}: d1=${roll.d1} [${meta.ANSWER}], d2=${roll.d2} [${meta.MOD}], ${meta.LIKELIHOOD}: ${likelihood})`;
    await this.plugin.historyManager.addEntry({
      id: crypto.randomUUID(),
      answer: content,
      raw,
      timestamp: Date.now(),
      type: "yesno",
      question: this.question
    });
    const markdown = MarkdownUtils.formatResult(title, content, raw);
    await MarkdownUtils.smartInsert(this.app, this.plugin, markdown);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/commands/oracle.ts
var OracleCommands = class {
  static registerCommands(plugin) {
    const app = plugin.app;
    plugin.addCommand({
      id: "opse-ask-how-much",
      name: `${t().ORACLE.HOW_MUCH}`,
      callback: async () => {
        const strings = t().ORACLE;
        const roll = Random.d(6);
        const content = strings.SCALES[roll - 1];
        const meta = t().METADATA;
        const raw = `(1d6=${roll})`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "howmuch"
        });
        const markdown = MarkdownUtils.formatResult(strings.HOW_MUCH, content, raw);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
      }
    });
    plugin.addCommand({
      id: "opse-roll-beat-move",
      name: "OPSE: Beat Move",
      callback: async () => {
        const roll = Random.d(6);
        const content = OPSE.getBeatMove(roll - 1);
        const meta = t().METADATA;
        const raw = `(1d6=${roll})`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "move"
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.HOOK, content, raw);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
      }
    });
    plugin.addCommand({
      id: "opse-roll-failure-move",
      name: "OPSE: Failure Move",
      callback: async () => {
        const roll = Random.d(6);
        const content = OPSE.getFailureMove(roll - 1);
        const meta = t().METADATA;
        const raw = `(1d6=${roll})`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "move"
        });
        const markdown = MarkdownUtils.formatResult("Failure Move", content, raw);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
      }
    });
    plugin.addCommand({
      id: "opse-focus-action",
      name: "OPSE: Action Focus",
      callback: async () => {
        const focus = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const content = OPSE.getAction(focus.rank);
        const domain = OPSE.getDomain(focus.suit);
        const meta = t().METADATA;
        const raw = `${plugin.settings.randomMode === "dice" ? `(${meta.DICE} Focus)` : `(${meta.DICE}: ${focus.rank} ${focus.suit})`}`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "focus",
          domain
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.NPC_FIELDS.GOAL, content, raw, domain);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
        if (focus.wasJoker) {
          new Notice(t().COMMON.JOKER_NOTICE);
          plugin.app.commands.executeCommandById("opse-oracle:opse-random-event");
        }
      }
    });
    plugin.addCommand({
      id: "opse-focus-detail",
      name: "OPSE: Detail Focus",
      callback: async () => {
        const focus = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const content = OPSE.getDetail(focus.rank);
        const domain = OPSE.getDomain(focus.suit);
        const meta = t().METADATA;
        const raw = `${plugin.settings.randomMode === "dice" ? `(${meta.DICE} Focus)` : `(${meta.DICE}: ${focus.rank} ${focus.suit})`}`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "focus",
          domain
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.HOOK, content, raw, domain);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
        if (focus.wasJoker) {
          new Notice(t().COMMON.JOKER_NOTICE);
          plugin.app.commands.executeCommandById("opse-oracle:opse-random-event");
        }
      }
    });
    plugin.addCommand({
      id: "opse-focus-double",
      name: "OPSE: Foco Doble (Acci\xF3n + Detalle)",
      callback: async () => {
        const focus1 = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const focus2 = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const action = OPSE.getAction(focus1.rank);
        const detail = OPSE.getDetail(focus2.rank);
        const domain = `${OPSE.getDomain(focus1.suit)} / ${OPSE.getDomain(focus2.suit)}`;
        const content = `${action} + ${detail}`;
        const meta = t().METADATA;
        const raw = `${plugin.settings.randomMode === "dice" ? `(${meta.DICE} Focus x2)` : `(${meta.DICE}: ${focus1.rank}${focus1.suit.charAt(0)}, ${focus2.rank}${focus2.suit.charAt(0)})`}`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "focus",
          domain
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.DOUBLE_FOCUS, content, raw, domain);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
        if (focus1.wasJoker || focus2.wasJoker) {
          new Notice(t().COMMON.JOKER_NOTICE);
          plugin.app.commands.executeCommandById("opse-oracle:opse-random-event");
        }
      }
    });
  }
};

// src/commands/generators.ts
var GeneratorCommands = class {
  static registerCommands(plugin) {
    const app = plugin.app;
    plugin.addCommand({
      id: "opse-random-event",
      name: "OPSE: Random Event",
      callback: async () => {
        const focus1 = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const focus2 = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const action = OPSE.getAction(focus1.rank);
        const theme = OPSE.getTheme(focus2.rank);
        const domain = OPSE.getDomain(focus1.suit);
        const meta = t().METADATA;
        const content = `${action} + ${theme}`;
        const raw = `${plugin.settings.randomMode === "dice" ? `(2d6 Focus)` : `(Cards: ${focus1.rank} ${focus1.suit}, ${focus2.rank} ${focus2.suit})`}`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "event",
          domain
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.GENERIC, content, raw, domain);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
        if (focus1.wasJoker || focus2.wasJoker) {
          new Notice(t().COMMON.JOKER_NOTICE);
          plugin.app.commands.executeCommandById("opse-oracle:opse-random-event");
        }
      }
    });
    plugin.addCommand({
      id: "opse-generate-hook",
      name: "OPSE: Plot Hook",
      callback: async () => {
        const r1 = Random.d(6);
        const r2 = Random.d(6);
        const r3 = Random.d(6);
        const strings = t().TABLES.HOOKS;
        const goal = strings.GOAL[r1 - 1];
        const adversary = strings.ADVERSARY[r2 - 1];
        const reward = strings.REWARD[r3 - 1];
        let content = `**${strings.GOAL_LABEL}:** ${goal}
`;
        content += `**${strings.ADVERSARY_LABEL}:** ${adversary}
`;
        content += `**${strings.REWARD_LABEL}:** ${reward}`;
        const meta = t().METADATA;
        const raw = `(3d6=${r1}, ${r2}, ${r3})`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "hook"
        });
        const markdown = MarkdownUtils.formatResult(strings.TITLE, content, raw);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
      }
    });
    plugin.addCommand({
      id: "opse-generate-npc",
      name: "OPSE: NPC Generator",
      callback: async () => {
        const focusId = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const focusGoal = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const traitRoll = Random.d(6);
        const focusDetail = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const attitudeRoll = Random.d(6);
        const focusTopic = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const identity = OPSE.getAction(focusId.rank);
        const goal = OPSE.getTheme(focusGoal.rank);
        const trait = `${OPSE.getComplication(traitRoll - 1)} / ${OPSE.getDetail(focusDetail.rank)}`;
        const attitudeResults = t().ORACLE.SCALES;
        const attitude = attitudeResults[attitudeRoll - 1];
        const topic = OPSE.getTheme(focusTopic.rank);
        const fields = t().ADVENTURE.NPC_FIELDS;
        let content = `**${fields.IDENTITY}:** ${identity}
`;
        content += `**${fields.GOAL}:** ${goal}
`;
        content += `**${fields.TRAIT}:** ${trait}
`;
        content += `**${fields.ATTITUDE}:** ${attitude}
`;
        content += `**${fields.TOPIC}:** ${topic}`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw: `(${t().ADVENTURE.NPC} / ${plugin.settings.randomMode})`,
          timestamp: Date.now(),
          type: "npc"
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.NPC, content, `(${t().METADATA.RESULT})`);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
        if (focusId.wasJoker || focusGoal.wasJoker || focusDetail.wasJoker || focusTopic.wasJoker) {
          new Notice(t().COMMON.JOKER_NOTICE);
          plugin.app.commands.executeCommandById("opse-oracle:opse-random-event");
        }
      }
    });
    plugin.addCommand({
      id: "opse-generate-generic",
      name: "OPSE: Generic Content",
      callback: async () => {
        const focusAction = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const focusDetail = Random.drawFocus(plugin.settings.randomMode, plugin.deck);
        const magnitudeRoll = Random.d(6);
        const action = OPSE.getAction(focusAction.rank);
        const appearance = OPSE.getDetail(focusDetail.rank);
        const magnitude = t().ORACLE.SCALES[magnitudeRoll - 1];
        const content = `${action} / ${appearance} (${magnitude})`;
        const meta = t().METADATA;
        const raw = `(Act: ${focusAction.rank}, Det: ${focusDetail.rank}, Mag: ${magnitudeRoll})`;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw,
          timestamp: Date.now(),
          type: "event"
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.GENERIC, content, raw);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
        if (focusAction.wasJoker || focusDetail.wasJoker) {
          new Notice(t().COMMON.JOKER_NOTICE);
          plugin.app.commands.executeCommandById("opse-oracle:opse-random-event");
        }
      }
    });
    plugin.addCommand({
      id: "opse-plot-twist",
      name: "OPSE: Giro de Trama",
      callback: async () => {
        const roll = Random.d(6);
        const content = OPSE.getPlotTwist(roll - 1);
        const meta = t().METADATA;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw: `(1d6=${roll})`,
          timestamp: Date.now(),
          type: "event"
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.PLOT_TWIST, content, `(1d6=${roll})`);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
      }
    });
    plugin.addCommand({
      id: "opse-flavor",
      name: "OPSE: Ambiente / Clima",
      callback: async () => {
        const rollAtm = Random.d(6);
        const rollWea = Random.d(6);
        const atmosphere = OPSE.getAtmosphere(rollAtm - 1);
        const weather = OPSE.getWeather(rollWea - 1);
        const content = `${atmosphere} / ${weather}`;
        const meta = t().METADATA;
        await plugin.historyManager.addEntry({
          id: crypto.randomUUID(),
          answer: content,
          raw: `(2d6 Focus: ${rollAtm}, ${rollWea})`,
          timestamp: Date.now(),
          type: "event"
        });
        const markdown = MarkdownUtils.formatResult(t().ADVENTURE.FLAVOR, content, `(2d6: ${rollAtm}, ${rollWea})`);
        await MarkdownUtils.smartInsert(app, plugin, markdown);
      }
    });
  }
};

// src/commands/exploration.ts
var import_obsidian9 = require("obsidian");

// src/ui/modals/dungeon-modal.ts
var import_obsidian6 = require("obsidian");

// src/core/dungeon.ts
var DungeonManager = class {
  static generateRoom(dungeon, name, fixedExits) {
    const id = crypto.randomUUID();
    const locations = ["Pasillo", "Habitaci\xF3n", "C\xE1mara", "Escaleras", "Puente", "Almac\xE9n"];
    const encounters = ["Ninguno", "Trampa", "Enemigo d\xE9bil", "Enemigo fuerte", "PNJ", "Peligro ambiental"];
    const objects = ["Ninguno", "Tesoro", "Herramienta", "Nota/Pista", "Mueble", "Estatua"];
    const room = {
      id,
      name,
      location: Random.pickOne(locations),
      encounter: Random.pickOne(encounters),
      object: Random.pickOne(objects),
      exits: fixedExits !== void 0 ? fixedExits : Random.d(4) - 1,
      connectedTo: [],
      notes: ""
    };
    if (room.exits < 0)
      room.exits = 0;
    dungeon.rooms[id] = room;
    dungeon.path.push(room.name || room.location);
    return room;
  }
  static createDungeon(name, appearance, func) {
    const dungeon = {
      id: crypto.randomUUID(),
      name,
      themeAppearance: appearance,
      themeFunction: func,
      rooms: {},
      currentRoomId: null,
      path: []
    };
    const firstRoom = this.generateRoom(dungeon, "Entrada", 3);
    dungeon.currentRoomId = firstRoom.id;
    return dungeon;
  }
  static moveToNextRoom(dungeon, name) {
    const currentRoom = dungeon.currentRoomId ? dungeon.rooms[dungeon.currentRoomId] : null;
    if (!currentRoom || currentRoom.exits <= 0)
      return null;
    currentRoom.exits--;
    const nextRoom = this.generateRoom(dungeon, name || `Sala ${dungeon.path.length + 1}`);
    currentRoom.connectedTo.push(nextRoom.id);
    nextRoom.connectedTo.push(currentRoom.id);
    dungeon.currentRoomId = nextRoom.id;
    return nextRoom;
  }
  static addRoomNote(dungeon, roomId, note) {
    if (dungeon.rooms[roomId]) {
      dungeon.rooms[roomId].notes = note;
    }
  }
};

// src/ui/modals/dungeon-modal.ts
var DungeonModal = class extends import_obsidian6.Modal {
  constructor(app, plugin) {
    super(app);
    __publicField(this, "plugin");
    __publicField(this, "name", "Mazmorra");
    __publicField(this, "appearance", "...");
    __publicField(this, "function", "...");
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Dungeon Tracker" });
    new import_obsidian6.Setting(contentEl).setName(t().ADVENTURE.TITLE).addText((text) => text.setValue(this.name).onChange((value) => this.name = value));
    new import_obsidian6.Setting(contentEl).setName("Appearance / Theme").addText((text) => text.setValue(this.appearance).onChange((value) => this.appearance = value));
    new import_obsidian6.Setting(contentEl).setName("Function / Purpose").addText((text) => text.setValue(this.function).onChange((value) => this.function = value));
    new import_obsidian6.Setting(contentEl).addButton((btn) => btn.setButtonText(t().ADVENTURE.START).setCta().onClick(() => {
      this.startDungeon();
      this.close();
    }));
  }
  startDungeon() {
    const dungeon = DungeonManager.createDungeon(this.name, this.appearance, this.function);
    const firstRoom = dungeon.rooms[dungeon.currentRoomId];
    let title = `Dungeon: ${this.name}`;
    let content = `**Theme:** ${this.appearance} (${this.function})

`;
    content += `**Entrance:** ${firstRoom.location}
`;
    content += `**Encounter:** ${firstRoom.encounter}
`;
    content += `**Object:** ${firstRoom.object}
`;
    content += `**Exits:** ${firstRoom.exits}`;
    const markdown = MarkdownUtils.formatResult(title, content, "(Start of dungeon crawl)");
    MarkdownUtils.insertAtCursor(this.app, markdown);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/modals/hex-modal.ts
var import_obsidian7 = require("obsidian");

// src/core/hex.ts
var HexManager = class {
  static getHexKey(q, r) {
    return `${q},${r}`;
  }
  static generateHex(region, q, r) {
    const roll = Random.d(12);
    let terrain = region.commonTerrain;
    if (roll === 10 || roll === 11)
      terrain = region.uncommonTerrain;
    if (roll === 12)
      terrain = region.rareTerrain;
    const contentsList = ["Ruinas", "Asentamiento", "Guarida", "Recurso", "Punto de inter\xE9s", "Nada notable"];
    const traits = ["Encantado", "Peligroso", "Sagrado", "Bello", "En ruinas", "Oculto"];
    const hex = {
      q,
      r,
      terrain,
      contents: Random.pickOne(contentsList),
      trait: Random.pickOne(traits),
      eventTriggered: Random.d(6) >= 5,
      notes: ""
    };
    region.hexes[this.getHexKey(q, r)] = hex;
    region.path.push(`${hex.terrain} (${q},${r})`);
    return hex;
  }
  static createRegion(name, common, uncommon, rare) {
    const region = {
      id: crypto.randomUUID(),
      name,
      commonTerrain: common,
      uncommonTerrain: uncommon,
      rareTerrain: rare,
      hexes: {},
      currentHex: { q: 0, r: 0 },
      path: []
    };
    this.generateHex(region, 0, 0);
    return region;
  }
  static moveToNeighbor(region, direction) {
    const current = region.currentHex;
    let dq = 0, dr = 0;
    switch (direction) {
      case "N":
        dq = 0;
        dr = -1;
        break;
      case "NE":
        dq = 1;
        dr = -1;
        break;
      case "SE":
        dq = 1;
        dr = 0;
        break;
      case "S":
        dq = 0;
        dr = 1;
        break;
      case "SW":
        dq = -1;
        dr = 1;
        break;
      case "NW":
        dq = -1;
        dr = 0;
        break;
    }
    const nq = current.q + dq;
    const nr = current.r + dr;
    const key = this.getHexKey(nq, nr);
    let hex = region.hexes[key];
    if (!hex) {
      hex = this.generateHex(region, nq, nr);
    }
    region.currentHex = { q: nq, r: nr };
    return hex;
  }
  static addHexNote(region, q, r, note) {
    const key = this.getHexKey(q, r);
    if (region.hexes[key]) {
      region.hexes[key].notes = note;
    }
  }
};

// src/ui/modals/hex-modal.ts
var HexModal = class extends import_obsidian7.Modal {
  constructor(app, plugin) {
    super(app);
    __publicField(this, "plugin");
    __publicField(this, "name", "Regi\xF3n");
    __publicField(this, "common", "...");
    __publicField(this, "uncommon", "...");
    __publicField(this, "rare", "...");
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Hex Exploration" });
    new import_obsidian7.Setting(contentEl).setName(t().ADVENTURE.TITLE).addText((text) => text.setValue(this.name).onChange((value) => this.name = value));
    new import_obsidian7.Setting(contentEl).setName("Common Terrain").addText((text) => text.setValue(this.common).onChange((value) => this.common = value));
    new import_obsidian7.Setting(contentEl).setName("Uncommon Terrain").addText((text) => text.setValue(this.uncommon).onChange((value) => this.uncommon = value));
    new import_obsidian7.Setting(contentEl).setName("Rare Terrain").addText((text) => text.setValue(this.rare).onChange((value) => this.rare = value));
    new import_obsidian7.Setting(contentEl).addButton((btn) => btn.setButtonText(t().ADVENTURE.START).setCta().onClick(() => {
      this.startRegion();
      this.close();
    }));
  }
  startRegion() {
    const region = HexManager.createRegion(this.name, this.common, this.uncommon, this.rare);
    const startHex = region.hexes[HexManager.getHexKey(0, 0)];
    let title = `Exploration: ${this.name}`;
    let content = `**Terrain Schema:** ${this.common} / ${this.uncommon} / ${this.rare}

`;
    content += `**Starting Hex (0,0):**
`;
    content += `**Terrain:** ${startHex.terrain}
`;
    content += `**Contents:** ${startHex.contents}
`;
    content += `**Trait:** ${startHex.trait}
`;
    if (startHex.eventTriggered)
      content += `**EVENT TRIGGERED!**
`;
    const markdown = MarkdownUtils.formatResult(title, content, "(Start of region exploration)");
    MarkdownUtils.insertAtCursor(this.app, markdown);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/exploration-view.ts
var import_obsidian8 = require("obsidian");
var VIEW_TYPE_OPSE_EXPLORATION = "opse-exploration-view";
var ExplorationView = class extends import_obsidian8.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_OPSE_EXPLORATION;
  }
  getDisplayText() {
    return "OPSE Exploration";
  }
  getIcon() {
    return "map";
  }
  async onOpen() {
    this.refresh();
  }
  refresh() {
    const container = this.containerEl.children[1];
    container.empty();
    const activeAdventure = this.plugin.adventureManager.getActiveAdventure();
    if (!activeAdventure) {
      container.createEl("p", { text: "No active adventure. Start one to enable exploration trackers.", cls: "opse-muted" });
      return;
    }
    const explorationRoot = container.createDiv({ cls: "opse-exploration-root" });
    if (activeAdventure.dungeonId && this.plugin.settings.dungeons[activeAdventure.dungeonId]) {
      this.renderDungeon(explorationRoot, this.plugin.settings.dungeons[activeAdventure.dungeonId]);
    }
    if (activeAdventure.regionId && this.plugin.settings.regions[activeAdventure.regionId]) {
      this.renderRegion(explorationRoot, this.plugin.settings.regions[activeAdventure.regionId]);
    }
    if (!activeAdventure.dungeonId && !activeAdventure.regionId) {
      container.createEl("p", { text: "No active dungeon or region. Use the command palette to start exploring." });
    }
  }
  renderDungeon(parent, dungeon) {
    const card = parent.createDiv({ cls: "opse-exploration-card" });
    card.createEl("h3", { text: `Dungeon: ${dungeon.name}` });
    card.createEl("p", { text: `${dungeon.themeAppearance} / ${dungeon.themeFunction}`, cls: "opse-muted" });
    const currentRoom = dungeon.currentRoomId ? dungeon.rooms[dungeon.currentRoomId] : null;
    if (currentRoom) {
      const roomEl = card.createDiv({ cls: "opse-current-location" });
      roomEl.createEl("h4", { text: `Sala: ${currentRoom.name}` });
      roomEl.createEl("p", { text: `\u{1F4CD} ${currentRoom.location}` });
      roomEl.createEl("p", { text: `\u{1F480} ${currentRoom.encounter}` });
      roomEl.createEl("p", { text: `\u{1F48E} ${currentRoom.object}` });
      roomEl.createEl("p", { text: `\u{1F6AA} Exits: ${currentRoom.exits}` });
      const controls = card.createDiv({ cls: "opse-exploration-controls" });
      if (currentRoom.connectedTo.length > 0) {
        const backRow = controls.createDiv({ cls: "opse-navigation-row" });
        backRow.createEl("span", { text: "Volver a: ", cls: "opse-label" });
        currentRoom.connectedTo.forEach((targetId) => {
          const targetRoom = dungeon.rooms[targetId];
          if (targetRoom) {
            const btn = backRow.createEl("button", { text: targetRoom.name, cls: "opse-nav-btn" });
            btn.addEventListener("click", async () => {
              dungeon.currentRoomId = targetId;
              dungeon.path.push(`Retroceder: ${targetRoom.name}`);
              await this.plugin.saveSettings();
              this.refresh();
            });
          }
        });
      }
      if (currentRoom.exits > 0) {
        const exploreBtn = controls.createEl("button", { text: "Explorar nueva \xE1rea", cls: "opse-action-btn" });
        exploreBtn.addEventListener("click", async () => {
          DungeonManager.moveToNextRoom(dungeon);
          await this.plugin.saveSettings();
          this.refresh();
        });
      } else {
        controls.createEl("p", { text: "No quedan salidas en esta sala.", cls: "opse-alert" });
      }
      const noteInput = card.createEl("textarea", { cls: "opse-interpretation-edit", attr: { placeholder: "A\xF1adir notas a la sala...", value: currentRoom.notes || "" } });
      noteInput.addEventListener("change", async (e) => {
        currentRoom.notes = e.target.value;
        await this.plugin.saveSettings();
      });
    }
    this.renderPathMap(card, dungeon.path);
  }
  renderRegion(parent, region) {
    const card = parent.createDiv({ cls: "opse-exploration-card" });
    card.createEl("h3", { text: `Region: ${region.name}` });
    const currentHex = region.hexes[`${region.currentHex.q},${region.currentHex.r}`];
    if (currentHex) {
      const hexEl = card.createDiv({ cls: "opse-current-location" });
      hexEl.createEl("h4", { text: `Hex: (${currentHex.q}, ${currentHex.r})` });
      hexEl.createEl("p", { text: `\u{1F332} ${currentHex.terrain}` });
      hexEl.createEl("p", { text: `\u{1F3DB}\uFE0F ${currentHex.contents}` });
      hexEl.createEl("p", { text: `\u2728 ${currentHex.trait}` });
      card.createEl("h5", { text: "Moverse:" });
      const compass = card.createDiv({ cls: "opse-compass-grid" });
      const directions = ["NW", "N", "NE", "SW", "S", "SE"];
      directions.forEach((dir) => {
        const btn = compass.createEl("button", { text: dir });
        btn.addEventListener("click", async () => {
          HexManager.moveToNeighbor(region, dir);
          await this.plugin.saveSettings();
          this.refresh();
        });
      });
      const noteInput = card.createEl("textarea", { cls: "opse-interpretation-edit", attr: { placeholder: "A\xF1adir notas al hex\xE1gono...", value: currentHex.notes || "" } });
      noteInput.addEventListener("change", async (e) => {
        currentHex.notes = e.target.value;
        await this.plugin.saveSettings();
      });
    }
    this.renderPathMap(card, region.path);
  }
  renderPathMap(parent, path) {
    if (path && path.length > 0) {
      const mapEl = parent.createDiv({ cls: "opse-path-map" });
      mapEl.createEl("h5", { text: "Mapa de Ruta:" });
      const pathText = path.join(" \u2794 ");
      mapEl.createDiv({ text: pathText, cls: "opse-path-text" });
    }
  }
};

// src/commands/exploration.ts
var ExplorationCommands = class {
  static registerCommands(plugin) {
    plugin.addCommand({
      id: "opse-create-dungeon",
      name: "Crear rastreador de mazmorra",
      callback: () => {
        new DungeonModal(plugin.app, plugin).open();
      }
    });
    plugin.addCommand({
      id: "opse-create-hex-region",
      name: "Crear regi\xF3n de hex\xE1gonos",
      callback: () => {
        new HexModal(plugin.app, plugin).open();
      }
    });
    plugin.addCommand({
      id: "opse-explore-room",
      name: "Explorar siguiente \xE1rea de la mazmorra",
      callback: async () => {
        const active = plugin.adventureManager.getActiveAdventure();
        if (active && active.dungeonId) {
          const dungeon = plugin.settings.dungeons[active.dungeonId];
          if (dungeon) {
            const next = DungeonManager.moveToNextRoom(dungeon);
            if (next) {
              await plugin.saveSettings();
              new import_obsidian9.Notice(`Nueva sala explorada: ${next.name}`);
              const leaf = plugin.app.workspace.getLeavesOfType(VIEW_TYPE_OPSE_EXPLORATION)[0];
              if (leaf)
                leaf.view.refresh();
            } else {
              new import_obsidian9.Notice("No hay m\xE1s salidas disponibles en esta sala.");
            }
          }
        } else {
          new import_obsidian9.Notice("No hay ninguna mazmorra activa.");
        }
      }
    });
    plugin.addCommand({
      id: "opse-explore-hex",
      name: "Moverse al Norte (Regi\xF3n Hex)",
      callback: async () => {
        const active = plugin.adventureManager.getActiveAdventure();
        if (active && active.regionId) {
          const region = plugin.settings.regions[active.regionId];
          if (region) {
            HexManager.moveToNeighbor(region, "N");
            await plugin.saveSettings();
            new import_obsidian9.Notice(`Desplazado al Norte.`);
            const leaf = plugin.app.workspace.getLeavesOfType(VIEW_TYPE_OPSE_EXPLORATION)[0];
            if (leaf)
              leaf.view.refresh();
          }
        } else {
          new import_obsidian9.Notice("No hay ninguna regi\xF3n de hex\xE1gonos activa.");
        }
      }
    });
  }
};

// src/ui/control-view.ts
var import_obsidian11 = require("obsidian");

// src/utils/exporter.ts
var import_obsidian10 = require("obsidian");
var ExportUtils = class {
  static async exportSession(app, plugin) {
    try {
      const history = plugin.historyManager.getHistory();
      if (history.length === 0)
        return false;
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const fileName = `OPSE-Session-${timestamp}.md`;
      let content = `# OPSE Session Report
`;
      content += `Exported on: ${new Date().toLocaleString()}

`;
      const meta = t().METADATA;
      history.forEach((entry) => {
        content += `### ${new Date(entry.timestamp).toLocaleTimeString()} - ${entry.type.toUpperCase()}
`;
        if (entry.question)
          content += `**${meta.RESULT}:** ${entry.question}
`;
        content += `**${meta.ANSWER}:** ${entry.answer}
`;
        if (entry.domain)
          content += `*${meta.DOMAIN}:* ${entry.domain}
`;
        if (entry.interpretation)
          content += `*${meta.NOTE}:* ${entry.interpretation}
`;
        content += `*${meta.RAW}:* ${entry.raw}

---

`;
      });
      let folderPath = "/";
      const activeFile = app.workspace.getActiveFile();
      if (activeFile && activeFile.parent) {
        folderPath = activeFile.parent.path;
      }
      const fullPath = (0, import_obsidian10.normalizePath)(`${folderPath}/${fileName}`);
      await app.vault.create(fullPath, content);
      return true;
    } catch (e) {
      console.error(e);
      return false;
    }
  }
};

// src/ui/control-view.ts
var VIEW_TYPE_OPSE_CONTROL = "opse-control-view";
var ControlPanelView = class extends import_obsidian11.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_OPSE_CONTROL;
  }
  getDisplayText() {
    return t().DASHBOARD.TITLE;
  }
  getIcon() {
    return "dice";
  }
  async onOpen() {
    this.refresh();
  }
  refresh() {
    var _a, _b;
    const container = this.containerEl.children[1];
    container.empty();
    const mainRoot = container.createDiv({ cls: "opse-unified-root" });
    const activeAdventure = this.plugin.adventureManager.getActiveAdventure();
    const scrollRoot = mainRoot.createDiv({ cls: "opse-control-root" });
    if (activeAdventure) {
      const adventureDetails = scrollRoot.createEl("details", { cls: "opse-adventure-card" });
      adventureDetails.createEl("summary", { text: activeAdventure.title });
      const content = adventureDetails.createDiv({ cls: "opse-section-content" });
      const rankRow = content.createDiv({ cls: "opse-rank-row" });
      rankRow.createSpan({ text: `${t().DASHBOARD.RANK}: `, cls: "opse-label" });
      rankRow.createSpan({ text: ((_a = activeAdventure.sceneRank) != null ? _a : 1).toString(), cls: "opse-rank-value" });
      const rankControls = rankRow.createDiv({ cls: "opse-rank-controls" });
      const rankMinus = rankControls.createEl("button", { text: "-", cls: "opse-rank-btn" });
      rankMinus.addEventListener("click", async () => {
        var _a2;
        await this.plugin.adventureManager.setSceneRank(activeAdventure.activeNotePath, ((_a2 = activeAdventure.sceneRank) != null ? _a2 : 1) - 1);
        this.refresh();
      });
      const rankPlus = rankControls.createEl("button", { text: "+", cls: "opse-rank-btn" });
      rankPlus.addEventListener("click", async () => {
        var _a2;
        await this.plugin.adventureManager.setSceneRank(activeAdventure.activeNotePath, ((_a2 = activeAdventure.sceneRank) != null ? _a2 : 1) + 1);
        this.refresh();
      });
      const threadSection = content.createDiv({ cls: "opse-thread-section" });
      threadSection.createEl("h5", { text: t().DASHBOARD.THREADS });
      const threadList = threadSection.createDiv({ cls: "opse-thread-list" });
      ((_b = activeAdventure.threads) != null ? _b : []).forEach((thread, index) => {
        const item = threadList.createDiv({ cls: "opse-thread-item" });
        item.createSpan({ text: thread });
        const delBtn = item.createEl("button", { text: "\xD7", cls: "opse-del-btn" });
        delBtn.addEventListener("click", async () => {
          await this.plugin.adventureManager.removeThread(activeAdventure.activeNotePath, index);
          this.refresh();
        });
      });
      const addThreadRow = threadSection.createDiv({ cls: "opse-add-thread" });
      const threadInput = addThreadRow.createEl("input", { attr: { placeholder: t().DASHBOARD.NEW_THREAD } });
      const addBtn = addThreadRow.createEl("button", { text: "+" });
      addBtn.addEventListener("click", async () => {
        if (threadInput.value) {
          await this.plugin.adventureManager.addThread(activeAdventure.activeNotePath, threadInput.value);
          this.refresh();
        }
      });
    }
    this.createCollapsibleSection(scrollRoot, t().ADVENTURE.NEW, [
      { text: t().ADVENTURE.NEW, callback: () => new AdventureModal(this.app, this.plugin).open() }
    ], false);
    this.createCollapsibleSection(scrollRoot, t().SCENE.NEW, [
      { text: t().SCENE.GENERATE, callback: () => new SceneModal(this.app, this.plugin).open() },
      { text: t().SCENE.CHECK_ALTERATION, callback: () => this.handleCheckAlteration() },
      { text: t().SCENE.ALTERED_ONLY, callback: () => this.handleAlteredRoll() },
      { text: t().SCENE.COMPLICATION_BTN, callback: () => this.handleComplicationRoll() }
    ], true);
    this.createCollapsibleSection(scrollRoot, t().ORACLE.TITLE, [
      { text: t().ORACLE.ASK, callback: () => new OracleModal(this.app, this.plugin).open() },
      { text: t().ORACLE.HOW_MUCH, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-ask-how-much") }
    ], true);
    this.createCollapsibleSection(scrollRoot, t().ORACLE.FOCUS_TITLE, [
      { text: t().ORACLE.ACTION, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-focus-action") },
      { text: t().ORACLE.DETAIL, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-focus-detail") },
      { text: t().ADVENTURE.DOUBLE_FOCUS, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-focus-double") }
    ], true);
    this.createCollapsibleSection(scrollRoot, t().DASHBOARD.GENERATORS, [
      { text: t().ADVENTURE.NPC, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-generate-npc") },
      { text: t().ADVENTURE.PLOT_TWIST, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-plot-twist") },
      { text: t().ADVENTURE.HOOK, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-generate-hook") },
      { text: t().ADVENTURE.GENERIC, callback: () => this.app.commands.executeCommandById("opse-oracle:opse-generate-generic") }
    ], true);
    this.createCollapsibleSection(scrollRoot, t().DASHBOARD.SESSION, [
      {
        text: t().DASHBOARD.EXPORTAR,
        callback: async () => {
          const success = await ExportUtils.exportSession(this.app, this.plugin);
          if (success)
            new import_obsidian11.Notice(t().EXPORT.SUCCESS);
          else
            new import_obsidian11.Notice(t().EXPORT.ERROR);
        }
      },
      {
        text: t().DASHBOARD.BARAJAR,
        callback: () => {
          this.plugin.deck.shuffle();
          new import_obsidian11.Notice(t().DASHBOARD.SHUFFLE_SUCCESS);
        }
      }
    ], false);
    const helpDetails = scrollRoot.createEl("details", { cls: "opse-control-section opse-help-details" });
    helpDetails.createEl("summary", { text: t().HELP.TITLE });
    const helpContent = helpDetails.createDiv({ cls: "opse-section-content opse-help-content" });
    helpContent.createEl("p", { text: t().HELP.SCENE_STEREOTYPE });
    helpContent.createEl("p", { text: t().HELP.SCENE_ALTERED });
    helpContent.createEl("p", { text: t().HELP.EVENT_TRIGGER });
    helpContent.createEl("p", { text: t().HELP.GM_MOVES });
    const historyWrapper = mainRoot.createDiv({ cls: "opse-history-wrapper" });
    historyWrapper.createEl("h4", { text: t().DASHBOARD.HISTORY });
    const historyRoot = historyWrapper.createDiv({ cls: "opse-history-root" });
    const entries = this.plugin.historyManager.getHistory();
    if (entries.length === 0) {
      historyRoot.createEl("p", { text: t().DASHBOARD.NO_HISTORY, cls: "opse-muted" });
    } else {
      entries.forEach((entry) => this.renderEntry(historyRoot, entry));
    }
  }
  createCollapsibleSection(parent, title, actions, open = false) {
    const details = parent.createEl("details", { cls: "opse-control-section" });
    if (open)
      details.setAttribute("open", "");
    details.createEl("summary", { text: title });
    const content = details.createDiv({ cls: "opse-section-content" });
    const grid = content.createDiv({ cls: "opse-control-grid" });
    actions.forEach((action) => {
      const btn = grid.createEl("button", { text: action.text });
      btn.addEventListener("click", action.callback);
    });
  }
  renderEntry(parent, entry) {
    const card = parent.createDiv({ cls: `opse-history-card ${entry.pinned ? "is-pinned" : ""}` });
    const pinBtn = card.createEl("button", { cls: `opse-pin-btn ${entry.pinned ? "is-active" : ""}`, title: entry.pinned ? t().COMMON.UNPIN : t().COMMON.PIN });
    (0, import_obsidian11.setIcon)(pinBtn, "pin");
    pinBtn.addEventListener("click", async () => {
      entry.pinned = !entry.pinned;
      await this.plugin.saveSettings();
      this.refresh();
    });
    const header = card.createDiv({ cls: "opse-history-header" });
    header.createSpan({ text: entry.type.toUpperCase(), cls: "opse-type-tag" });
    header.createSpan({ text: new Date(entry.timestamp).toLocaleTimeString(), cls: "opse-timestamp" });
    if (entry.question) {
      card.createDiv({ text: entry.question, cls: "opse-history-question" });
    }
    const content = card.createDiv({ cls: "opse-history-content" });
    content.createEl("strong", { text: entry.answer });
    if (entry.domain) {
      card.createDiv({ text: entry.domain, cls: "opse-history-domain" });
    }
    card.createDiv({ text: entry.raw, cls: "opse-history-raw" });
    const interpretationEdit = card.createEl("input", {
      cls: "opse-interpretation-edit",
      attr: {
        placeholder: t().METADATA.NOTE + "...",
        value: entry.interpretation || ""
      }
    });
    interpretationEdit.addEventListener("change", async (e) => {
      entry.interpretation = e.target.value;
      await this.plugin.saveSettings();
    });
    const actions = card.createDiv({ cls: "opse-history-actions" });
    const copyBtn = actions.createEl("button", { cls: "opse-action-btn", title: t().COMMON.COPY });
    (0, import_obsidian11.setIcon)(copyBtn, "copy");
    copyBtn.createSpan({ text: t().COMMON.COPY });
    copyBtn.addEventListener("click", () => {
      const formatted = MarkdownUtils.formatResult(entry.question ? `${t().METADATA.RESULT}: ${entry.question}` : entry.type, entry.answer, entry.raw, entry.domain, entry.interpretation);
      navigator.clipboard.writeText(formatted);
      new import_obsidian11.Notice(t().COMMON.COPIED);
    });
    const insertBtn = actions.createEl("button", { cls: "opse-action-btn", title: t().COMMON.INSERT });
    (0, import_obsidian11.setIcon)(insertBtn, "edit");
    insertBtn.createSpan({ text: t().COMMON.INSERT });
    insertBtn.addEventListener("click", async () => {
      var _a;
      const markdown = MarkdownUtils.formatResult(entry.question ? `${entry.type}: ${entry.question}` : entry.type, entry.answer, entry.raw, entry.domain, entry.interpretation);
      await MarkdownUtils.insertAtCursor(this.app, markdown, (_a = this.plugin.adventureManager.getActiveAdventure()) == null ? void 0 : _a.activeNotePath);
    });
    const rerollBtn = actions.createEl("button", { cls: "opse-action-btn", title: t().COMMON.REROLL });
    (0, import_obsidian11.setIcon)(rerollBtn, "refresh-cw");
    rerollBtn.createSpan({ text: t().COMMON.REROLL });
    rerollBtn.addEventListener("click", () => {
      this.handleReroll(entry);
    });
  }
  handleReroll(entry) {
    const commandsMap = {
      "yesno": "opse-oracle:opse-ask-oracle",
      "howmuch": "opse-oracle:opse-ask-how-much",
      "focus": "opse-oracle:opse-focus-action",
      "event": "opse-oracle:opse-random-event",
      "move": "opse-oracle:opse-roll-beat-move",
      "npc": "opse-oracle:opse-generate-npc",
      "hook": "opse-oracle:opse-generate-hook"
    };
    const cmdId = commandsMap[entry.type];
    if (cmdId) {
      this.app.commands.executeCommandById(cmdId);
    }
  }
  async handleCheckAlteration() {
    const roll = Random.d(6);
    const isAltered = roll >= 5;
    const result = isAltered ? t().SCENE.ALTERED_NOTICE : t().SCENE.NOT_ALTERED;
    const meta = t().METADATA;
    const raw = `(1d6=${roll} ${isAltered ? `>= 5` : `< 5`})`;
    await this.plugin.historyManager.addEntry({
      id: crypto.randomUUID(),
      answer: result,
      raw,
      timestamp: Date.now(),
      type: "scene"
    });
    const markdown = MarkdownUtils.formatResult(t().SCENE.CHECK_ALTERATION, result, raw);
    await MarkdownUtils.smartInsert(this.app, this.plugin, markdown);
    this.refresh();
    if (isAltered) {
      new import_obsidian11.Notice(result);
    }
  }
  async handleAlteredRoll() {
    const roll = Random.d(6);
    const result = OPSE.getAltered(roll);
    const meta = t().METADATA;
    const raw = `(1d6=${roll} [${meta.RESULT}])`;
    await this.plugin.historyManager.addEntry({
      id: crypto.randomUUID(),
      answer: result,
      raw,
      timestamp: Date.now(),
      type: "scene"
    });
    const markdown = MarkdownUtils.formatResult(t().SCENE.ALTERED_ONLY, result, raw);
    await MarkdownUtils.smartInsert(this.app, this.plugin, markdown);
    this.refresh();
  }
  async handleComplicationRoll() {
    const roll = Random.d(6);
    const result = OPSE.getComplication(roll - 1);
    const meta = t().METADATA;
    const raw = `(1d6=${roll} [${meta.COMPLICATION}])`;
    await this.plugin.historyManager.addEntry({
      id: crypto.randomUUID(),
      answer: result,
      raw,
      timestamp: Date.now(),
      type: "scene"
    });
    const markdown = MarkdownUtils.formatResult(t().SCENE.COMPLICATION_BTN, result, raw);
    await MarkdownUtils.smartInsert(this.app, this.plugin, markdown);
    this.refresh();
  }
  async handleDirectOracle(likelihood) {
    const strings = t().ORACLE;
    const roll = Random.roll2d6();
    const { answer, modifier } = OPSE.resolveYesNo(roll.d1, roll.d2, likelihood);
    let content = `${answer}${modifier ? ` ${modifier}` : ""}`;
    let raw = `(d1=${roll.d1} [Respuesta], d2=${roll.d2} [Mod], Prob: ${likelihood})`;
    await this.plugin.historyManager.addEntry({
      id: crypto.randomUUID(),
      answer: content,
      raw,
      timestamp: Date.now(),
      type: "yesno"
    });
    const markdown = MarkdownUtils.formatResult(t().ORACLE.YESNO_TITLE, content, raw);
    await MarkdownUtils.smartInsert(this.app, this.plugin, markdown);
    this.refresh();
  }
  async onClose() {
  }
};

// src/core/deck.ts
var Deck = class {
  constructor(useJokers = false) {
    __publicField(this, "cards", []);
    __publicField(this, "discard", []);
    __publicField(this, "useJokers", false);
    this.useJokers = useJokers;
    this.reset();
  }
  reset() {
    this.cards = [];
    this.discard = [];
    const suits = ["Hearts" /* Hearts */, "Diamonds" /* Diamonds */, "Clubs" /* Clubs */, "Spades" /* Spades */];
    const ranks = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
    for (const suit of suits) {
      for (let i = 0; i < ranks.length; i++) {
        this.cards.push({
          rank: ranks[i],
          suit,
          value: i + 1
        });
      }
    }
    if (this.useJokers) {
      this.cards.push({ rank: "Joker", suit: "Joker" /* Joker */, value: 0 });
      this.cards.push({ rank: "Joker", suit: "Joker" /* Joker */, value: 0 });
    }
    this.shuffle();
  }
  shuffle() {
    for (let i = this.cards.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [this.cards[i], this.cards[j]] = [this.cards[j], this.cards[i]];
    }
  }
  draw() {
    if (this.cards.length === 0) {
      this.cards = [...this.discard];
      this.discard = [];
      this.shuffle();
    }
    if (this.cards.length === 0) {
      this.reset();
    }
    const card = this.cards.pop();
    this.discard.push(card);
    if (card.suit === "Joker" /* Joker */) {
      this.reset();
    }
    return card;
  }
  getRemainingCount() {
    return this.cards.length;
  }
  getDiscardCount() {
    return this.discard.length;
  }
};

// src/main.ts
var OPSEOraclePlugin = class extends import_obsidian12.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "adventureManager");
    __publicField(this, "historyManager");
    __publicField(this, "deck");
  }
  async onload() {
    await this.loadSettings();
    I18n.setLanguage(this.settings.language);
    this.addRibbonIcon("dice", "OPSE Control", () => {
      this.activateView(VIEW_TYPE_OPSE_CONTROL);
    });
    this.deck = new Deck();
    if (this.settings.randomMode === "persistent_deck") {
    }
    this.adventureManager = new AdventureStateManager(this.settings, async (s) => await this.saveSettings(s));
    this.historyManager = new HistoryManager(this.settings.history, 100, async (h) => {
      this.settings.history = h;
      await this.saveSettings();
      this.refreshViews();
    });
    this.registerView(VIEW_TYPE_OPSE_CONTROL, (leaf) => new ControlPanelView(leaf, this));
    this.registerView(VIEW_TYPE_OPSE_EXPLORATION, (leaf) => new ExplorationView(leaf, this));
    this.addSettingTab(new OPSESettingTab(this.app, this));
    this.addCommand({
      id: "opse-open-control",
      name: `OPSE: ${t().SETTINGS.OPEN_CONTROL}`,
      callback: () => this.activateView(VIEW_TYPE_OPSE_CONTROL)
    });
    this.addCommand({
      id: "opse-open-history",
      name: `OPSE: ${t().SETTINGS.OPEN_HISTORY}`,
      callback: () => this.activateView(VIEW_TYPE_OPSE_CONTROL)
    });
    this.addCommand({
      id: "opse-open-exploration",
      name: `OPSE: ${t().SETTINGS.OPEN_EXPLORATION}`,
      callback: () => this.activateView(VIEW_TYPE_OPSE_EXPLORATION)
    });
    this.addCommand({
      id: "opse-start-adventure",
      name: `OPSE: ${t().ADVENTURE.NEW}`,
      callback: () => new AdventureModal(this.app, this).open()
    });
    this.addCommand({
      id: "opse-set-scene",
      name: `OPSE: ${t().SCENE.NEW}`,
      callback: () => new SceneModal(this.app, this).open()
    });
    this.addCommand({
      id: "opse-ask-oracle",
      name: `OPSE: ${t().ORACLE.YESNO_TITLE}`,
      callback: () => new OracleModal(this.app, this).open()
    });
    OracleCommands.registerCommands(this);
    GeneratorCommands.registerCommands(this);
    ExplorationCommands.registerCommands(this);
    console.log("OPSE Oracle plugin loaded");
  }
  async activateView(type) {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(type);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({ type, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  refreshViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_OPSE_EXPLORATION).forEach((leaf) => {
      if (leaf.view instanceof ExplorationView)
        leaf.view.refresh();
    });
    this.app.workspace.getLeavesOfType(VIEW_TYPE_OPSE_CONTROL).forEach((leaf) => {
      if (leaf.view instanceof ControlPanelView)
        leaf.view.refresh();
    });
  }
  onunload() {
    console.log("OPSE Oracle plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings(settings) {
    if (settings)
      this.settings = settings;
    await this.saveData(this.settings);
  }
};
